spring:
  h2:
    console:
      enable: true

  datasource:
    url: jdbc:mysql://localhost:3306/dev_day?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
logging:
  level:
    com.tutorial: debug

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd2tYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK